### ISSUE TITLE
BUG: breaks kedro-viz (not handling save_version = None)

### ISSUE THREAD

**Issue by king-michael** [neptune-ai/kedro-neptune#39]
### Describe the bug
When using other kedro commands, like `kedro viz`, the package brakes.
This is because no `save_version` is initialized by other commands and the plugin currently doesn't handle the case.
This problem is also existent in the current version. (Traceback is for 0.0.7)
See: https://github.com/neptune-ai/kedro-neptune/blob/f975c03e739db8e8eb5ab45555430ff23b8facc9/kedro_neptune/__init__.py#L417

### Reproduction
Install kedro viz
`pip install kedro-viz`

Add an exception in the `src/my_package_name/settings.py`
```
# List the installed plugins for which to disable auto-registry
DISABLE_HOOKS_FOR_PLUGINS = ("kedro-viz",)
```

run
```
kedro viz
```

### Expected behavior
Kedro viz works as excpeted.
Optimal, It is recognized that this is not a `kedro run` so no neptune session is initalized.
Minimal,It is recognized that no save_version is present, (catalog is created separately) no `run_id` is calculated.

### Traceback
Command: `kedro viz`
Traceback:
```
2022-05-23 16:32:15,384 - kedro.framework.hooks.manager - INFO - Registered hooks from 1 installed plugin(s): kedro-neptune-0.0.7
2022-05-23 16:32:17,411 - kedro_viz.integrations.pypi - INFO - Checking for update...
2022-05-23 16:32:18,141 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.
2022-05-23 16:32:18,340 - ProjectHooks - INFO - register_catalog(self.env='local', save_version=None, load_versions=None, journal=None)
Traceback (most recent call last):
  File "C:\PATH\TO\ENV\lib\site-packages\kedro_viz\launchers\cli.py", line 122, in viz
    run_server(**run_server_kwargs)
  File "C:\PATH\TO\ENV\lib\site-packages\kedro_viz\server.py", line 75, in run_server
    catalog, pipelines, session_store_location = kedro_data_loader.load_data(
  File "C:\PATH\TO\ENV\lib\site-packages\kedro_viz\integrations\kedro\data_loader.py", line 68, in load_data
    catalog = context.catalog
  File "C:\PATH\TO\ENV\lib\site-packages\kedro\framework\context\context.py", line 320, in catalog
    return self._get_catalog()
  File "C:\PATH\TO\ENV\lib\site-packages\kedro\framework\context\context.py", line 383, in _get_catalog
    hook_manager.hook.after_catalog_created(  # pylint: disable=no-member
  File "C:\PATH\TO\ENV\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\PATH\TO\ENV\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\PATH\TO\ENV\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "C:\PATH\TO\ENV\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "C:\PATH\TO\ENV\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\PATH\TO\ENV\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\PATH\TO\ENV\lib\site-packages\kedro_neptune\__init__.py", line 415, in after_catalog_created
    self._run_id = hashlib.md5(run_id.encode()).hexdigest()
AttributeError: 'NoneType' object has no attribute 'encode'
kedro.framework.cli.utils.KedroCliError: 'NoneType' object has no attribute 'encode'
Run with --verbose to see the full exception
Error: 'NoneType' object has no attribute 'encode'
```

### Additional context
Even when the `None` case is handled, a new error could arise due to creating a neptune experiment for every run of a kedro viz command.

**Comment by Blaizzy** [comment]
Hi @king-michael,

Prince Canuma here, a Data Scientist at Neptune.ai,

Thank you for reporting the issue, I have reached out to the engineering team to investigate this. As soon as I have any news or updates from the team, I will let you know!

**Comment by Blaizzy** [comment]
Hi @king-michael,

Good news!!! 

I have talked to the engineering team and we have a new release of the kedro neptune integration (v0.1.1) that allows you to use environment variables. 

You can use the environment variables to set Neptune to debug mode or disable it and when you are using kedro viz which I think will solve your problem,

Let me know if this works for you!

Release link:
https://github.com/neptune-ai/kedro-neptune/releases/tag/0.1.1

**Comment by Blaizzy** [comment]
Hi @king-michael,

I'm just checking in to see if you still need help with this or if you have any other questions.

**Comment by fabz1** [comment]
Hi @Blaizzy,
I'm running into the same problem, with kedro==0.18.2 and kedro-neptune==0.1.1. Can you maybe clarify what the suggested solution would be? Just using enabled: false in neptune.yml doesn't solve the problem for me and still produces the error above. Kedro-viz only works if you temporarily disable hooks for kedro-neptune by adding DISABLE_HOOKS_FOR_PLUGINS =("kedro-neptune") in settings.py

**Comment by Blaizzy** [comment]
Hey @fabz1,

In the newest release, you can enable and disable Neptune by setting the `NEPTUNE_ENABLED` environment variable passing either `True` or `False`.

Example:
`export NEPTUNE_ENABLED='False'`

PR: https://github.com/neptune-ai/kedro-neptune/pull/35

Let me know if this works for you

**Comment by fabz1** [comment]
Hi @Blaizzy,
thanks but that doesn't work for me. The only option is to temporarily disable hooks in settings.py while visualizing the pipeline.

**Comment by Blaizzy** [comment]
No problem, 

I will talk to the devs and get back to you,

Meanwhile is there anything else I can help you with?

**Comment by Blaizzy** [comment]
Hey @king-michael and @fabz1 

The fix is on production and your issue should disappear now! 🎉

Let me know if it works for you or not,

Looking forward to hearing from you.
